import {units,reviewId} from './curriculum.js';
import {topics,generate,options,isCorrect,matchPairs,shuffle,story} from './data.js';
import {load,save,settle,badges} from './storage.js';
import {modes,start,answer} from './engine.js';
const $=s=>document.querySelector(s),main=$('#main');let profile=load(),course=1,unit=null,topic=null,g=null,current=null,locked=false,timer=null,questionStart=0,deadline=0,reading=null,pairs=[],selected=null,seen=new Set(),toastTimer;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n.toLocaleString();
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
let audio;
function sound(kind){if(!profile.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),a=audio.createGain();o.type='sine';o.frequency.setValueAtTime(kind==='bad'?180:kind==='end'?780:560,audio.currentTime);a.gain.setValueAtTime(.045,audio.currentTime);a.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.connect(a);a.connect(audio.destination);o.start();o.stop(audio.currentTime+.17);}catch{}}
function settings(){document.body.classList.toggle('light',profile.light);$('#sound').textContent=profile.sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',profile.sound);$('#theme').textContent=profile.light?'Dark mode':'Light mode';$('#theme').setAttribute('aria-pressed',profile.light);}
$('#sound').onclick=()=>{profile.sound=!profile.sound;save(profile);settings();sound('good');};$('#theme').onclick=()=>{profile.light=!profile.light;save(profile);settings();};
$('.brand').onclick=e=>{e.preventDefault();leave();};
function leave(){if(g&&!g.ended&&!confirm('Leave this round? Only completed rounds save XP and records.'))return;home();}
function home(){clearInterval(timer);g=null;const bests=Object.entries(profile.bests).filter(([k])=>k.endsWith(':quick')||k.endsWith(':story')||k.endsWith(':speed')).map(([,v])=>v);main.innerHTML=`<section class="intro"><div><div class="eyebrow">YOUR NEXT HIGH SCORE STARTS HERE</div><h1>A little Spanish.<br>A lot of “one more.”</h1><p>Pick a unit. Practice your way. Beat your best.</p></div><div class="stats"><div><small>Best score</small><strong>${bests.length?Math.max(...bests):'—'}<small>${bests.length?'OUT OF 100':'PLAY TO SET'}</small></strong></div><div><small>Best streak</small><strong>${profile.bestStreak} <span aria-hidden="true">ϟ</span></strong></div><div><small>Total XP</small><strong>${fmt(profile.xp)}</strong></div></div></section><section class="setup" aria-label="Game setup"><div><span class="label">01 / YOUR COURSE</span><div class="segmented">${[1,2].map(c=>`<button data-course="${c}" aria-pressed="${course===c}" class="${course===c?'active':''}">Spanish ${c}</button>`).join('')}</div></div><div class="level"><div class="level-line"><strong>Level ${Math.floor(profile.xp/250)+1}</strong><span>${profile.xp%250} / 250 XP</span></div><div class="bar" aria-label="Progress to next level"><span style="width:${profile.xp%250/2.5}%"></span></div></div></section>${curriculumView()}${topic?`<div class="label">04 / PICK YOUR GAME</div><section class="games" aria-label="Game modes">${modes.map((m,i)=>`<button class="game-card ${i===0?'featured':''}" data-mode="${m.id}"><span class="symbol" aria-hidden="true">${m.icon}</span><span class="go" aria-hidden="true">↗</span><span class="tag">${m.tag}</span><h3>${m.name}</h3><p>${m.desc}</p></button>`).join('')}</section>`:''}<details class="badge-section"><summary>Achievements · ${profile.achievements.length} / ${badges.length} unlocked</summary><div class="badges">${badges.map(([id,n,d])=>`<div class="badge ${profile.achievements.includes(id)?'':'locked'}">${profile.achievements.includes(id)?'★':'◇'} ${n}<small>${d}</small></div>`).join('')}</div></details>`;
main.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{course=Number(b.dataset.course);unit=null;topic=null;home();main.querySelector(`[data-course="${course}"]`).focus();});
main.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>{unit=units[course].find(u=>u.id===b.dataset.unit);topic=null;home();$('#content-title').focus();});
main.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{topic=b.dataset.topic;home();main.querySelector(`[data-topic="${topic}"]`).focus();});
$('#change-unit')?.addEventListener('click',()=>{const previous=unit?.id;unit=null;topic=null;home();(main.querySelector(`[data-unit="${previous}"]`)||$('#unit-title')).focus();});
$('#course-review')?.addEventListener('click',()=>{unit=null;topic='mixed';home();$('#change-unit').focus();});
main.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>begin(b.dataset.mode));}
function contentLabel(){return topic?.startsWith('unit:')?`${unit.name} · Mixed review`:topics[course][topic];}
function curriculumView(){
 if(!unit&&topic!=='mixed')return `<section class="curriculum" aria-labelledby="unit-title"><h2 id="unit-title" tabindex="-1">02 / Choose your unit</h2><div class="unit-grid">${units[course].map((u,i)=>`<button class="unit-card" data-unit="${u.id}"><span class="unit-icon" aria-hidden="true">${u.icon}</span><span><small>UNIT ${i+1}</small><strong>${esc(u.name)}</strong><span class="unit-meta">${u.topics.length} ${u.topics.length===1?'topic':'topics'} · Mixed review</span></span><span aria-hidden="true">→</span></button>`).join('')}</div><button id="course-review" class="quiet">Review all of Spanish ${course} ↗</button></section>`;
 if(!unit)return `<section class="curriculum"><div class="curriculum-heading"><h2>All-course mixed review</h2><button id="change-unit" class="quiet">← Choose a unit</button></div></section>`;
 return `<section class="curriculum" aria-labelledby="content-title"><div class="curriculum-heading"><div><span class="eyebrow">SPANISH ${course} / UNIT ${units[course].indexOf(unit)+1}</span><h2 id="content-title" tabindex="-1">${esc(unit.name)}</h2></div><button id="change-unit" class="quiet">← Units</button></div><span class="label">03 / CHOOSE YOUR PRACTICE</span><div class="topic-grid">${[[reviewId(unit),'Mixed review', 'Every topic in this unit'],...unit.topics.map(t=>[t,topics[course][t],'Focus on this topic'])].map(([id,name,hint])=>`<button class="topic-card ${topic===id?'active':''}" data-topic="${id}" aria-pressed="${topic===id}"><strong>${esc(name)}</strong><small>${hint}</small></button>`).join('')}</div>${topic?`<p class="selection-summary" role="status">Ready: ${esc(contentLabel())}. Pick a game below.</p>`:''}</section>`;
}
function begin(mode){clearInterval(timer);if(!topic)return;g=start(course,topic,mode);reading=mode==='story'?story(course,topic):null;seen=new Set();selected=null;pairs=[];deadline=Date.now()+60000;const m=modes.find(x=>x.id===mode);main.innerHTML=`<section class="game-shell"><div class="game-top"><div><span class="eyebrow">SPANISH ${course} / ${esc(contentLabel())}</span><h2>${m.name}</h2></div><button id="leave" class="quiet">← Games</button></div><p>${m.detail}</p><div class="hud" style="margin-top:20px"><div class="metric"><small id="score-label">Score</small><strong id="score">0</strong></div><div class="metric"><small>Streak</small><strong id="streak">0 ϟ</strong></div><div class="metric"><small id="progress-label">Progress</small><strong id="progress">0 / 10</strong></div></div><div class="bar"><span id="progress-bar" style="width:0%"></span></div>${reading?`<details class="reading" open><summary>${reading.title}</summary><p lang="es">${esc(reading.text)}</p></details>`:''}<div id="arena"></div></section>`;$('#leave').onclick=leave;if(mode==='match'){renderMatch();return;}next();timer=setInterval(tick,100);}
function next(){if(!g||g.ended)return;if(g.mode==='minute'&&Date.now()>=deadline){finish();return;}locked=false;current=reading?reading.questions[g.attempts]:generate(course,topic);for(let tries=0;!reading&&seen.has(current.prompt)&&tries<25;tries++)current=generate(course,topic);seen.add(current.prompt);questionStart=Date.now();const mc=['minute','speed','story'].includes(g.mode)||g.attempts<2||g.streak===0||Math.random()<(g.streak>=3?.25:.55);current.choices=mc?options(current):null;$('#arena').innerHTML=`<section class="question"><div class="eyebrow">${mc?'CHOOSE YOUR ANSWER':'YOUR TURN · TYPE IT'}</div><h2 id="prompt">${esc(current.prompt)}</h2>${mc?`<div class="choices">${current.choices.map((c,i)=>`<button class="choice" data-choice="${i}"><span class="key" aria-hidden="true">${i+1}</span><span>${esc(c)}</span></button>`).join('')}</div>`:`<form id="answer-form"><label class="label" for="typed">Your answer</label><input id="typed" autocomplete="off" autocapitalize="off" spellcheck="false" aria-describedby="typing-hint"><div class="input-actions"><div class="accent-keys" aria-label="Spanish letters">${['á','é','í','ó','ú','ñ','ü'].map(c=>`<button type="button" data-letter="${c}" aria-label="Insert ${c}">${c}</button>`).join('')}</div><button class="primary" type="submit">Check answer</button></div><p class="hint" id="typing-hint">Vowel accents are optional. ñ is a different letter from n.</p></form>`}<div id="feedback" aria-live="polite"></div></section>`;if(mc){main.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>submit(current.choices[Number(b.dataset.choice)]));}else{$('#answer-form').onsubmit=e=>{e.preventDefault();if($('#typed').value.trim())submit($('#typed').value);};main.querySelectorAll('[data-letter]').forEach(b=>b.onclick=()=>{const input=$('#typed');input.setRangeText(b.dataset.letter,input.selectionStart,input.selectionEnd,'end');input.focus();});}updateHUD();(mc?$('.choice'):$('#typed')).focus({preventScroll:true});}
function submit(value,timeout=false){if(!g||g.ended||locked)return;if(g.mode==='minute'&&Date.now()>=deadline){finish();return;}if(g.mode==='speed'&&Date.now()-questionStart>=8000&&!timeout){submit('',true);return;}locked=true;const ok=!timeout&&isCorrect(value,current);const end=answer(g,ok,Math.max(0,8-(Date.now()-questionStart)/1000));g.history.push({prompt:current.prompt,answer:current.answers[0],value:timeout?'Time ran out':value,ok});main.querySelectorAll('.choice,input,#answer-form button').forEach(b=>b.disabled=true);main.querySelectorAll('.choice').forEach((b,i)=>{if(isCorrect(current.choices[i],current))b.classList.add('correct');else if(current.choices[i]===value)b.classList.add('wrong');});$('#feedback').className='feedback '+(ok?'':'miss');$('#feedback').innerHTML=`<strong>${ok?'✓ ¡Correcto!':timeout?'◷ Time’s up.':'↻ Not quite.'}</strong><p>${ok?`+${g.streak%5===0?20:10} XP${g.streak>=3?' · Streak '+g.streak+'!':''}`:'Correct answer: '+esc(current.answers[0])}</p>${ok?'':`<small>${esc(current.explanation)}</small>`}<button id="next" class="primary">${end?'See results':'Continue'} →</button>`;sound(ok?'good':'bad');if(ok&&[3,5,10,20,30].includes(g.streak))toast(`ϟ ${g.streak} in a row! Keep it going.`);$('#next').onclick=end?finish:next;$('#next').focus({preventScroll:true});updateHUD();}
function tick(){if(!g||g.ended)return;if(g.mode==='minute'&&Date.now()>=deadline){finish();return;}if(g.mode==='speed'&&!locked&&Date.now()-questionStart>=8000){submit('',true);}updateHUD();}
function updateHUD(){if(!g||g.ended)return;const mode=g.mode;$('#score-label').textContent=['minute','lives'].includes(mode)?'Arcade points':mode==='streak'?'Best this round':mode==='match'?'Accuracy':'Score';$('#score').textContent=mode==='streak'?g.bestStreak:mode==='match'?(g.attempts?Math.round(g.correct/g.attempts*100):0)+'%':['minute','lives'].includes(mode)?fmt(Math.round(g.points)):g.score+' / 100';$('#streak').textContent=g.streak+' ϟ';let progress='',pct=0,label='Progress';if(mode==='minute'){const left=Math.max(0,(deadline-Date.now())/1000);progress=Math.ceil(left)+'s';pct=left/60*100;label='Time left';}else if(mode==='speed'){const left=locked?0:Math.max(0,8-(Date.now()-questionStart)/1000);progress=left.toFixed(1)+'s';pct=left/8*100;label=`Question ${Math.min(10,g.attempts+(locked?0:1))} / 10`;}else if(mode==='lives'){progress='♥'.repeat(Math.max(0,g.lives))+'♡'.repeat(Math.min(3,3-g.lives));pct=g.attempts/30*100;label='Lives · '+g.attempts+' / 30';}else if(mode==='streak'){progress=g.attempts+' / 30';pct=g.attempts/30*100;}else if(mode==='match'){progress=((Date.now()-g.started)/1000).toFixed(1)+'s';pct=g.correct/6*100;label=g.correct+' / 6 pairs';}else{let total=mode==='story'?5:10;progress=g.attempts+' / '+total;pct=g.attempts/total*100;}$('#progress-label').textContent=label;$('#progress').textContent=progress;$('#progress-bar').style.width=pct+'%';}
function renderMatch(){pairs=matchPairs(course,topic);$('#arena').innerHTML=`<section class="question"><p style="margin-bottom:20px">Choose a Spanish tile, then its English match.</p><div class="match-grid">${['es','en'].map(side=>`<div class="match-column" aria-label="${side==='es'?'Spanish':'English'}">${shuffle(pairs).map(p=>`<button class="tile" data-side="${side}" data-pair="${p.id}" aria-pressed="false" ${side==='es'?'lang="es"':''}>${esc(p[side])}</button>`).join('')}</div>`).join('')}</div><p id="match-feedback" aria-live="polite" class="hint">Six pairs. You’ve got this.</p></section>`;main.querySelectorAll('.tile').forEach(b=>b.onclick=()=>matchClick(b));timer=setInterval(updateHUD,100);updateHUD();$('.tile').focus();}
function matchClick(b){if(g.ended)return;if(b.dataset.side==='es'){main.querySelectorAll('[data-side="es"]').forEach(t=>{t.classList.remove('selected');t.setAttribute('aria-pressed','false');});selected=b;b.classList.add('selected');b.setAttribute('aria-pressed','true');return;}if(!selected){$('#match-feedback').textContent='Choose a Spanish tile first.';return;}const a=selected,ok=a.dataset.pair===b.dataset.pair;answer(g,ok);a.classList.remove('selected');a.setAttribute('aria-pressed','false');selected=null;if(ok){a.disabled=b.disabled=true;a.classList.add('matched');b.classList.add('matched');a.textContent+=' ✓';b.textContent+=' ✓';$('#match-feedback').textContent='✓ Matched! +10 XP';sound('good');}else{const p=pairs.find(p=>String(p.id)===a.dataset.pair);$('#match-feedback').textContent=`Not quite. ${p.es} = ${p.en}. Try again.`;g.history.push({prompt:p.es,answer:p.en,value:b.textContent,ok:false});sound('bad');}updateHUD();if(g.correct===6)finish();else main.querySelector('[data-side="es"]:not(:disabled)')?.focus();}
function finish(){if(!g||g.ended)return;g.ended=true;g.completed=true;g.elapsed=Math.round((Date.now()-g.started)/100)/10;clearInterval(timer);if(g.mode==='match')g.score=Math.round(g.correct/g.attempts*100);const reward=settle(profile,g),m=modes.find(x=>x.id===g.mode),accuracy=g.attempts?Math.round(g.correct/g.attempts*100):0;const key=`${g.course}:${g.topic}:${g.mode}`;const metric=g.mode==='streak'?g.bestStreak:['minute','lives'].includes(g.mode)?Math.round(g.points):g.mode==='match'?g.elapsed:g.score;const suffix=g.mode==='streak'?'in a row':g.mode==='match'?'sec':['minute','lives'].includes(g.mode)?'pts':'/ 100';const bestLabel=g.mode==='match'?'Best time':g.mode==='streak'?'Best streak':'Personal best';main.innerHTML=`<section class="result"><div class="eyebrow">${m.name} · SPANISH ${course}</div><h1>${g.score===100&&g.correct>0?'¡Perfecto!':g.correct===0?'Your next round starts fresh.':'That’s a round. Ready for another?'}</h1>${reward.record?'<div class="record">★ NEW PERSONAL BEST</div>':''}<div class="result-score">${fmt(metric)} <span>${suffix}</span></div><p>${bestLabel}: ${fmt(profile.bests[key])}${g.mode==='match'?' sec':''} · ${esc(contentLabel())}</p><div class="stats"><div><small>Accuracy</small><strong>${accuracy}%</strong></div><div><small>Correct</small><strong>${g.correct} / ${g.attempts}</strong></div><div><small>Best streak</small><strong>${g.bestStreak}</strong></div><div><small>XP earned</small><strong>+${reward.xp}</strong></div></div><p>Level ${Math.floor(profile.xp/250)+1} · ${fmt(profile.xp)} total XP · ${g.elapsed.toFixed(1)} seconds</p>${!reward.saved?'<p>Progress could not be saved in this browser. You can still keep playing.</p>':''}<div class="result-actions"><button class="primary" id="again">↻ Play again</button><button id="games">Choose a game</button></div>${reward.unlocked.length?`<div class="record">★ ${reward.unlocked.map(id=>badges.find(b=>b[0]===id)[1]).join(' · ')}</div>`:''}${g.history.some(h=>!h.ok)?`<details class="review"><summary>A little practice for next time · ${g.history.filter(h=>!h.ok).length} to review</summary><ul>${g.history.filter(h=>!h.ok).map(h=>`<li>${esc(h.prompt)}<br><small>Your answer: ${esc(h.value)}</small><br><strong>✓ ${esc(h.answer)}</strong></li>`).join('')}</ul></details>`:'<p>Keep the momentum. A fresh round is one click away.</p>'}</section>`;$('#again').onclick=()=>begin(g.mode);$('#games').onclick=home;$('#again').focus({preventScroll:true});sound('end');if(reward.unlocked.length)toast('★ Achievement unlocked: '+badges.find(b=>b[0]===reward.unlocked[0])[1]);window.scrollTo({top:0,behavior:'instant'});}
document.addEventListener('keydown',e=>{if(e.repeat||e.altKey||e.ctrlKey||e.metaKey||e.target.matches('input,select,textarea'))return;if(g&&!g.ended&&!locked&&current?.choices&&g.mode!=='match'&&/^[1-4]$/.test(e.key)){const b=main.querySelector(`[data-choice="${Number(e.key)-1}"]`);if(b){e.preventDefault();b.click();}}});
settings();home();
