// Five grounded comprehension questions per topic. No network or runtime dependencies.
const passage=(title,text,items)=>({title,text,questions:items.map(([prompt,answer,...wrong])=>[prompt,answer,wrong])});
export const readings={
 greetings:passage('Un día de saludos','Por la mañana, Ana dice: «Buenos días, profesora». La profesora responde: «Hola, Ana». Por la tarde, Ana dice: «Buenas tardes, Luis». Luis presenta a su amiga y Ana dice: «Mucho gusto». Al salir, Ana dice: «Hasta mañana».',[
 ['What does Ana say in the morning?','Buenos días','Buenas tardes','Hasta mañana'],['Who says “Hola, Ana”?','la profesora','Luis','la amiga'],['When does Ana greet Luis?','por la tarde','por la mañana','por la noche'],['What does Ana say when meeting a new friend?','Mucho gusto','Adiós','Buenas noches'],['When does Ana expect to see them again?','tomorrow','tonight','next month']]),
 introductions:passage('Conoce a Ana','Me llamo Ana. Soy de México. Tengo quince años. Mi amigo se llama Luis. Él es de Ecuador y tiene dieciséis años. Hoy estoy bien, pero Luis está cansado.',[
 ['What is the narrator’s name?','Ana','Luis','Eva'],['Where is Ana from?','México','Ecuador','España'],['How old is Ana?','15','16','14'],['Where is Luis from?','Ecuador','México','Chile'],['How does Luis feel?','tired','well','sad']]),
 numbers:passage('En el salón','En el salón hay treinta estudiantes. Tenemos veinte libros y cuarenta lápices. En mi mochila hay dos cuadernos. La profesora tiene cien tarjetas para un juego.',[
 ['How many students are there?','30','13','40'],['How many books are there?','20','12','30'],['How many pencils are there?','40','14','20'],['How many notebooks are in the backpack?','2','12','20'],['How many game cards does the teacher have?','100','50','10']]),
 days:passage('Mi semana','El lunes estudio español. El martes dibujo. El miércoles canto. El jueves estudio arte. El viernes bailo con mis amigos. El sábado y el domingo no tengo clases.',[
 ['On which day does the narrator study Spanish?','lunes','martes','viernes'],['On which day does the narrator draw?','martes','lunes','jueves'],['On which day does the narrator sing?','miércoles','sábado','viernes'],['On which day does the narrator study art?','jueves','martes','domingo'],['On which day does the narrator dance?','viernes','lunes','miércoles']]),
 months:passage('Nuestro calendario','Mi cumpleaños es en enero. El cumpleaños de Ana es en marzo. Tenemos un concierto en mayo. Las clases empiezan en agosto. En diciembre visitamos a la familia.',[
 ['When is the narrator’s birthday?','enero','junio','marzo'],['When is Ana’s birthday?','marzo','mayo','abril'],['When is the concert?','mayo','marzo','julio'],['When do classes start?','agosto','enero','febrero'],['When do they visit family?','diciembre','septiembre','octubre']]),
 time:passage('Un día ocupado','La clase de español es a las ocho. La clase de arte es a las diez y cuarto. El almuerzo es a las doce y media. La clase de música es a la una. El partido es a las tres y cinco.',[
 ['What time is Spanish class?','8:00','9:00','8:30'],['What time is art class?','10:15','10:30','10:05'],['What time is lunch?','12:30','12:00','1:30'],['What time is music class?','1:00','11:00','2:00'],['What time is the game?','3:05','3:50','3:15']]),
 colors:passage('Mi mochila','Mi mochila es azul. Dentro hay un cuaderno rojo y un libro verde. Mi lápiz es amarillo. La profesora tiene una carpeta morada.',[
 ['What color is the backpack?','blue','red','green'],['What color is the notebook?','red','yellow','purple'],['What color is the book?','green','blue','black'],['What color is the pencil?','yellow','red','white'],['What color is the teacher’s folder?','purple','green','gray']]),
 weather:passage('Una semana de clima','El lunes hace sol. El martes llueve. El miércoles hace viento. El jueves está nublado. El viernes hace frío y nieva. ¡El clima cambia mucho!',[
 ['What is the weather like on Monday?','sunny','rainy','cloudy'],['What happens on Tuesday?','it rains','it snows','it is sunny'],['What is the weather like on Wednesday?','windy','snowy','hot'],['What is the weather like on Thursday?','cloudy','sunny','rainy'],['What happens on Friday?','it snows','it is hot','it rains']]),
 subjects:passage('Las clases de mis amigos','Mi clase favorita es español. A Ana le gusta historia. Luis prefiere ciencias. Eva estudia arte y dibuja mucho. A Pablo le gusta educación física porque le gusta correr.',[
 ['What is the narrator’s favorite class?','Spanish','math','English'],['Which subject does Ana like?','history','science','music'],['Which subject does Luis prefer?','science','art','history'],['Which subject does Eva study?','art','math','Spanish'],['Which subject does Pablo like?','physical education','music','English']]),
 family:passage('La familia de Elena','Me llamo Elena. Mi madre se llama Rosa y mi padre se llama Luis. Tengo un hermano, Mateo, y una hermana, Ana. Mi abuela Carmen es la madre de Rosa. Mi tío Pedro es el hermano de Luis. La hija de Pedro se llama Julia; ella es mi prima. Los domingos visitamos a mis abuelos.',[
 ['Who is Elena’s mother?','Rosa','Carmen','Ana'],['Who is Elena’s brother?','Mateo','Luis','Pedro'],['How is Carmen related to Elena?','grandmother','aunt','sister'],['How is Pedro related to Elena?','uncle','father','grandfather'],['How is Julia related to Elena?','cousin','niece','daughter']]),
 pronouns:passage('Nuestro grupo','Yo soy Ana. Tú eres mi amigo Luis. Ella es nuestra profesora, la señora Díaz. Nosotros somos estudiantes: Luis y yo. Ellos son Pedro y Miguel, dos amigos de otra clase.',[
 ['Which pronoun does Ana use for herself?','yo','tú','ella'],['Which pronoun addresses Luis directly?','tú','él','ellos'],['Who does “ella” refer to?','la señora Díaz','Ana','Luis'],['Who does “nosotros” refer to?','Ana y Luis','Pedro y Miguel','Luis y la profesora'],['Who does “ellos” refer to?','Pedro y Miguel','Ana y Luis','Ana y la profesora']]),
 ser:passage('Somos estudiantes','Soy Eva y soy estudiante. Mi amigo Luis es de Ecuador. Ana y yo somos de México. La profesora es paciente. Luis y Pedro son creativos. Nuestra clase es interesante.',[
 ['What is Eva?','estudiante','profesora','doctora'],['Where is Luis from?','Ecuador','México','España'],['Who is from Mexico?','Eva y Ana','Luis y Pedro','la profesora'],['How is the teacher described?','paciente','impaciente','tímida'],['Who is creative?','Luis y Pedro','Eva y Ana','la profesora']]),
 adjectives:passage('Personas diferentes','Mi hermana Ana es alta y creativa. Mi hermano Luis es bajo y paciente. Mis primas son simpáticas. Mis abuelos son trabajadores. Mi amiga Eva es inteligente y organizada.',[
 ['Who is tall and creative?','Ana','Luis','Eva'],['How is Luis described?','bajo y paciente','alto y creativo','serio y tímido'],['How are the female cousins described?','simpáticas','tímidas','serias'],['How are the grandparents described?','trabajadores','atléticos','bajos'],['Who is intelligent and organized?','Eva','Ana','Luis']]),
 gusta:passage('Lo que me gusta','Me llamo Diego. Me gusta bailar y escuchar música. No me gusta correr. A mi amiga Ana le gusta leer, pero no le gusta cantar. Los dos disfrutamos la clase de español.',[
 ['Does Diego like dancing?','yes','no','the text does not say'],['What does Diego like listening to?','music','the radio news','podcasts'],['What does Diego dislike?','running','dancing','listening to music'],['What does Ana like?','reading','singing','running'],['What does Ana dislike?','singing','reading','Spanish class']]),
 ar:passage('Una tarde activa','Yo estudio español en casa. Mi hermana Ana dibuja un mapa. Mi padre trabaja en una tienda. Mis amigos bailan en el parque. Por la noche, Ana y yo escuchamos música.',[
 ['¿Qué estudio?','español','historia','arte'],['¿Qué dibuja Ana?','un mapa','una casa','un gato'],['¿Dónde trabaja mi padre?','en una tienda','en casa','en el parque'],['¿Qué hacen mis amigos?','bailan','cantan','estudian'],['¿Qué hacemos Ana y yo por la noche?','escuchamos música','compramos libros','caminamos']]),
 er:passage('En la biblioteca','Yo leo un libro en la biblioteca. Ana aprende español. Luis bebe agua. Nosotros comemos fruta. Después, Ana y Luis corren en el parque.',[
 ['¿Qué leo?','un libro','un mensaje','una revista'],['¿Qué aprende Ana?','español','inglés','francés'],['¿Qué bebe Luis?','agua','leche','jugo'],['¿Qué comemos?','fruta','pan','arroz'],['¿Dónde corren Ana y Luis?','en el parque','en la biblioteca','en casa']]),
 ir:passage('Un mensaje para Julia','Yo vivo en Nashville. Mi amiga Julia vive en Quito. Escribo un mensaje para Julia. Ella recibe el mensaje por la mañana. En clase, mis amigos y yo compartimos los libros. La profesora abre la puerta.',[
 ['¿Dónde vivo?','Nashville','Quito','Madrid'],['¿Dónde vive Julia?','Quito','Nashville','Bogotá'],['¿Qué escribo?','un mensaje','un libro','un poema'],['¿Cuándo recibe Julia el mensaje?','por la mañana','por la tarde','por la noche'],['¿Qué compartimos en clase?','los libros','la comida','los lápices']])
};
